# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{netscaler-cli}
  s.version = "0.3.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Gabe McArthur"]
  s.date = %q{2010-12-03}
  s.description = %q{This gem installs several simple command line utilities locally.  It uses the NSConfig.wsdl SOAP interface for remote access.}
  s.email = ["madeonamac@gmail.com"]
  s.executables = ["netscaler-vserver", "netscaler-service", "netscaler-server"]
  s.extra_rdoc_files = [
    "README.markdown"
  ]
  s.files = [
    "Gemfile",
    "Gemfile.lock",
    "README.markdown",
    "Rakefile",
    "bin/netscaler-server",
    "bin/netscaler-service",
    "bin/netscaler-vserver",
    "lib/netscaler/baseexecutor.rb",
    "lib/netscaler/clitemplate.rb",
    "lib/netscaler/config.rb",
    "lib/netscaler/errors.rb",
    "lib/netscaler/logging.rb",
    "lib/netscaler/server/cli.rb",
    "lib/netscaler/server/executor.rb",
    "lib/netscaler/service/cli.rb",
    "lib/netscaler/service/executor.rb",
    "lib/netscaler/transaction.rb",
    "lib/netscaler/version.rb",
    "lib/netscaler/vserver/cli.rb",
    "lib/netscaler/vserver/executor.rb",
    "spec/config_spec.rb",
    "spec/configs/bad-yaml.yml",
    "spec/configs/missing-username.yml",
    "spec/configs/simple-config.yml",
    "spec/helpers.rb",
    "spec/server/cli_spec.rb",
    "spec/service/cli_spec.rb",
    "spec/vserver/cli_spec.rb"
  ]
  s.homepage = %q{http://github.com/gabemc/netscaler-cli}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Simple command line utilities for interacting remotely with a Netscaler load balancer.}
  s.test_files = [
    "spec/config_spec.rb",
    "spec/helpers.rb",
    "spec/server/cli_spec.rb",
    "spec/service/cli_spec.rb",
    "spec/vserver/cli_spec.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<log4r>, ["~> 1.1"])
      s.add_runtime_dependency(%q<savon>, ["~> 0.7"])
      s.add_runtime_dependency(%q<highline>, [">= 1.6"])
      s.add_runtime_dependency(%q<log4r>, [">= 1.1.9"])
      s.add_runtime_dependency(%q<savon>, [">= 0.7.9"])
      s.add_runtime_dependency(%q<highline>, [">= 1.6"])
      s.add_development_dependency(%q<rspec>, [">= 2.2.0"])
    else
      s.add_dependency(%q<log4r>, ["~> 1.1"])
      s.add_dependency(%q<savon>, ["~> 0.7"])
      s.add_dependency(%q<highline>, [">= 1.6"])
      s.add_dependency(%q<log4r>, [">= 1.1.9"])
      s.add_dependency(%q<savon>, [">= 0.7.9"])
      s.add_dependency(%q<highline>, [">= 1.6"])
      s.add_dependency(%q<rspec>, [">= 2.2.0"])
    end
  else
    s.add_dependency(%q<log4r>, ["~> 1.1"])
    s.add_dependency(%q<savon>, ["~> 0.7"])
    s.add_dependency(%q<highline>, [">= 1.6"])
    s.add_dependency(%q<log4r>, [">= 1.1.9"])
    s.add_dependency(%q<savon>, [">= 0.7.9"])
    s.add_dependency(%q<highline>, [">= 1.6"])
    s.add_dependency(%q<rspec>, [">= 2.2.0"])
  end
end

